using System;
using System.Collections;
using System.Collections.Generic;
using TMPro;
using UnityEngine;
using UnityEngine.UI;

public class NewBehaviourScript : MonoBehaviour
{
    public TMP_Text dialogueText; 
    public Button continueButton;
    public GameObject dialoguePanel;

    private string[] dialogueSentences;
    private int sentenceIndex = 0;

    void Start()
    {
        Time.timeScale = 0f;
        dialogueSentences = new string[]
        {
            "Hello, and welcome to the year 2025!",
            "I am Dr. Tyrone, an esteemed scientist. I am researching cybernetics and future technologies to help humanity.",
            "To improve the rate of my research, I have invented a type of unit called \"Tech Points (TP)\".",
            "Tech points can be generated by stimulating brain cells.",
            "As you can see, there is a sealed brain in the middle of the room.",
            "This brain is surrounded by equipment which really should be upgraded.",
            "By clicking on the brain in the middle of the room, you will generate Tech Points.",
            "The amount of Tech Points you currently have in storage is shown in the screen on the right wall.",
            "Under that screen is a board with plans of possible future upgrades for the equipment to help improve your rate of research.",
            "It shows what can be upgraded, the price of the upgrades, and the level of how upgraded the equipment currently is.",
            "Click on the name of the equipment you want to upgrade to upgrade it, if you have the necessary amount of Tech Points.",
            "If you look at the back wall, there is a screen with a green brain diagram on it. Click on it to view your statistics.",
            "The main things you want to do are generate Tech Points by clicking on the brain ...",
            "... and buy upgrades for equipment using the upgrade board, by spending your accumulated Tech Points.",
            "I have some important things to do, so I am going to leave you with the responsibility of continuing the research.",
            "See you soon, and good luck!"
        };

        //Display the first sentence
        dialogueText.text = dialogueSentences[sentenceIndex];

        //Add the listener
        continueButton.onClick.AddListener(OnContinueClicked);
    }
    
    void OnContinueClicked()
    {
        sentenceIndex++;

        if (sentenceIndex < dialogueSentences.Length)
        {
            dialogueText.text = dialogueSentences[sentenceIndex];
        }
        else
        {
            //Hide the UI and resume time
            Time.timeScale = 1f;
            dialoguePanel.SetActive(false);
        }
    }
}
